services:

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=sd_db
      - POSTGRES_USER=sd_user
      - POSTGRES_PASSWORD=sd_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres-data: