server:
  port: 8081
spring:
  application:
    name: backend-bo
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sd_db}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:sd_user}
    password: ${DB_PASSWORD:sd_password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    open-in-view: false
  